#!/bin/bash

source ~/.bashrc
FILE=/media/files/other/autogenerated/do_not_lock_screen

if [ "$1" = "i3_hotkey" ]; then
    if [ -e "$FILE" ]; then
        mv "$FILE" "${FILE}1"
    fi
fi

if [ -e "$FILE" ]; then
    DO_LOCK=false
else
    DO_LOCK=true
fi

if [ "$DO_LOCK" = "false" ]; then
    exit
fi

set -e

setxkbmap us
# Turn off Caps_Lock if needed:
if xset q | grep -q 'Caps Lock:   on' ; then
	xdotool key Caps_Lock
fi
xmodmap ~/.Xmodmap
set +e # since Caps_Lock may be undefined, the following command may fail
xmodmap -e 'remove Lock = Caps_Lock' -e 'keysym Caps_Lock = BackSpace' 2>/dev/null
set -e

xset dpms force off
i3lock -c 101010 --nofork
setxkbmap us,ru

$DOTRC/other_files/init_keyboard_layout.sh
