#!/usr/bin/perl

use strict;
use warnings;

sub on_user_command {
    my ($self, $action) = @_;
    my $script = $ENV{'DOTRC'} . "/other_files/handle_terminal_buffer.py";
    my $arg = substr($action, index($action, ":") + 1);
    if (open(PIPE, "| $script $arg")) {
        # $self->top_row; # <-- 0 or negative number
        # First visible row: 0.
        # Last visible row (cursor may stay above): $self->nrow - 1.
        # Here row is in range [0; screen_height), column we don't need.
        my ($row, $column) = $self->screen_cur();
        # This loop includes the row we are standing on (latest command prompt):
        for (my $i = 0; $i <= $row; $i++) {
            my $row_text = $self->ROW_t($i);
            print PIPE "$row_text\n";
        }
        close(PIPE);
    } else {
        system("zenity --error --title 'urxvt' --text " .
            "'Runing command \"$script $arg\" failed.'");
    }
}
